import numpy as np
import pandas as pd

from part2_bp_implementation.NeuralNet import NeuralNet


def load_preprocessed_data():
    """
    Load the preprocessed data generated in Part 1 from .npy files.

    Requirement mapping (Part 1 -> Optional 1 bridge):
    - Reuses the same preprocessed / normalized input features X produced in Part 1.
    - Uses exactly the same 80% / 20% train+validation / test split as in Parts 2 and 3.
    - Ensures that the regularization study is based on the same data as the main models.
    """

    # Files are generated by part1_generate_files.py and used in all subsequent parts.
    X_train_val = np.load("./../dataset/preprocessed/X_train_val.npy")
    y_train_val = np.load("./../dataset/preprocessed/y_train_val.npy")
    X_test = np.load("./../dataset/preprocessed/X_test.npy")
    y_test = np.load("./../dataset/preprocessed/y_test.npy")

    # Ensure that targets are 2D column vectors: (n_samples, 1)
    if y_train_val.ndim == 1:
        y_train_val = y_train_val.reshape(-1, 1)
    if y_test.ndim == 1:
        y_test = y_test.reshape(-1, 1)

    print(f"Train+val X shape: {X_train_val.shape}, y shape: {y_train_val.shape}")
    print(f"Test      X shape: {X_test.shape}, y shape: {y_test.shape}")

    return X_train_val, y_train_val, X_test, y_test


def regression_metrics(y_true, y_pred):
    """
    Compute regression metrics in the original (descaled) units.

    Metrics:
    - Mean Squared Error (MSE)
    - Mean Absolute Error (MAE)
    - Mean Absolute Percentage Error (MAPE, in %)
    """

    y_true = np.asarray(y_true).reshape(-1, 1)
    y_pred = np.asarray(y_pred).reshape(-1, 1)

    mse = float(np.mean((y_true - y_pred) ** 2))
    mae = float(np.mean(np.abs(y_true - y_pred)))

    # Avoid division by zero when computing MAPE
    eps = 1e-8
    mape = float(np.mean(np.abs((y_true - y_pred) / (y_true + eps))) * 100.0)

    return mse, mae, mape


def train_bp_with_regularization(
    X_train_val,
    y_train_val_scaled,
    y_train_val_original,
    X_test,
    y_test_scaled,
    y_test_original,
    y_mean,
    y_std,
    l1_reg,
    l2_reg,
    epochs=100,
):
    """
    Train the custom BP network with given L1 and L2 regularization strengths.

    Requirement mapping (Optional 1):
    - Keeps the architecture and main hyperparameters fixed.
    - Varies only the regularization strengths (lambda_1, lambda_2).
    - Evaluates the impact of regularization on:
        * train and test errors (MSE, MAE, MAPE),
        * overall weight magnitude (to measure weight shrinkage).
    """

    # -------------------------------------------------------------------------
    # Step 1: Define the network architecture and base hyperparameters
    # -------------------------------------------------------------------------
    # We use a slightly larger network than in Part 3 so that regularization
    # has a visible effect on the weight magnitudes.
    n_features = X_train_val.shape[1]
    layers = [n_features, 20, 10, 1]

    nn = NeuralNet(
        layers=layers,
        learning_rate=0.01,
        momentum=0.5,
        fact="relu",      # Hidden activation: ReLU (commonly used with L2/L1)
        l1_reg=l1_reg,    # L1 regularization strength (lambda_1)
        l2_reg=l2_reg,    # L2 regularization strength (lambda_2)
    )

    print(
        f"  Training network with layers={layers}, "
        f"L1={l1_reg}, L2={l2_reg}, epochs={epochs}"
    )

    # -------------------------------------------------------------------------
    # Step 2: Fit the network on the standardized targets (train+validation)
    # -------------------------------------------------------------------------
    # The validation_split parameter ensures that a portion of train_val is used
    # internally for validation, as in Part 2.
    nn.fit(
        X=X_train_val,
        y=y_train_val_scaled,
        epochs=epochs,
        validation_split=0.2,
    )

    # -------------------------------------------------------------------------
    # Step 3: Obtain predictions on train+val and test sets
    # -------------------------------------------------------------------------
    # Predictions are obtained in standardized units and then descaled using
    # the same mean and standard deviation used for scaling the outputs.
    y_train_pred_scaled = nn.predict(X_train_val)
    y_test_pred_scaled = nn.predict(X_test)

    if y_train_pred_scaled.ndim == 1:
        y_train_pred_scaled = y_train_pred_scaled.reshape(-1, 1)
    if y_test_pred_scaled.ndim == 1:
        y_test_pred_scaled = y_test_pred_scaled.reshape(-1, 1)

    # Descale predictions back to original units (USD)
    y_train_pred = y_train_pred_scaled * y_std + y_mean
    y_test_pred = y_test_pred_scaled * y_std + y_mean

    # -------------------------------------------------------------------------
    # Step 4: Compute metrics in original units (USD)
    # -------------------------------------------------------------------------
    train_mse, train_mae, train_mape = regression_metrics(
        y_train_val_original, y_train_pred
    )
    test_mse, test_mae, test_mape = regression_metrics(
        y_test_original, y_test_pred
    )

    # -------------------------------------------------------------------------
    # Step 5: Measure overall weight magnitude (L1 and squared L2)
    # -------------------------------------------------------------------------
    # This gives a quantitative idea of how strong the regularization effect is.
    total_abs_weights = 0.0
    total_sq_weights = 0.0
    for l in range(1, nn.L):
        total_abs_weights += np.sum(np.abs(nn.w[l]))
        total_sq_weights += np.sum(nn.w[l] ** 2)

    result = {
        "l1_reg": l1_reg,
        "l2_reg": l2_reg,
        "train_mse": train_mse,
        "test_mse": test_mse,
        "train_mae": train_mae,
        "test_mae": test_mae,
        "train_mape": train_mape,
        "test_mape": test_mape,
        "total_abs_weights": total_abs_weights,
        "total_sq_weights": total_sq_weights,
    }
    return result


def main():
    """
    Run a grid search over L1 and L2 regularization strengths.

    Requirement mapping (Optional 1):
    - Tests at least 10 different (lambda_1, lambda_2) combinations.
    - Keeps architecture and other hyperparameters fixed to isolate the effect
      of regularization.
    - Produces a table of train/test metrics and weight magnitudes for the
      memory of the assignment.
    """

    np.random.seed(0)

    # -------------------------------------------------------------------------
    # Step 1: Load preprocessed data (same as in Parts 2 and 3)
    # -------------------------------------------------------------------------
    X_train_val, y_train_val, X_test, y_test = load_preprocessed_data()

    # -------------------------------------------------------------------------
    # Step 2: Standardize the output using train+val statistics
    # -------------------------------------------------------------------------
    # This is identical to the output preprocessing in Part 2 and Part 3.
    y_mean = y_train_val.mean(axis=0)
    y_std = y_train_val.std(axis=0)
    y_std[y_std == 0] = 1.0

    y_train_val_scaled = (y_train_val - y_mean) / y_std
    y_test_scaled = (y_test - y_mean) / y_std

    print("Output standardization for Optional 1:")
    print(f"  y_mean: {y_mean}")
    print(f"  y_std : {y_std}")

    # -------------------------------------------------------------------------
    # Step 3: Define the regularization grid (lambda_1, lambda_2) combinations
    # -------------------------------------------------------------------------
    # We explore different strengths of L1-only, L2-only and combined L1+L2.
    regularization_grid = [
        (0.0, 0.0),
        (1e-4, 0.0),
        (1e-3, 0.0),
        (0.0, 1e-4),
        (0.0, 1e-3),
        (1e-4, 1e-4),
        (1e-3, 1e-3),
        (1e-3, 1e-2),
        (1e-2, 0.0),
        (0.0, 1e-2),
    ]

    print(f"Testing {len(regularization_grid)} (L1, L2) configurations...")

    # -------------------------------------------------------------------------
    # Step 4: Train a BP model for each (L1, L2) configuration
    # -------------------------------------------------------------------------
    results = []
    for idx, (l1_reg, l2_reg) in enumerate(regularization_grid, start=1):
        print(f"\nConfiguration {idx}/{len(regularization_grid)}")
        res = train_bp_with_regularization(
            X_train_val=X_train_val,
            y_train_val_scaled=y_train_val_scaled,
            y_train_val_original=y_train_val,
            X_test=X_test,
            y_test_scaled=y_test_scaled,
            y_test_original=y_test,
            y_mean=y_mean,
            y_std=y_std,
            l1_reg=l1_reg,
            l2_reg=l2_reg,
            epochs=100,
        )
        results.append(res)

        print(
            f"  Test MSE: {res['test_mse']:.4f}, "
            f"Test MAE: {res['test_mae']:.4f}, "
            f"Test MAPE: {res['test_mape']:.4f}%, "
            f"Sum |w|: {res['total_abs_weights']:.2f}"
        )

    # -------------------------------------------------------------------------
    # Step 5: Build and save the summary table for the memory
    # -------------------------------------------------------------------------
    df = pd.DataFrame(results)
    df_sorted = df.sort_values(by="test_mse").reset_index(drop=True)

    print("\n--- Regularization tuning results (sorted by Test MSE) ---")
    print(df_sorted)

    df_sorted.to_csv("./regularization_tuning_results.csv", index=False)
    print("Saved results to regularization_tuning_results.csv")


if __name__ == "__main__":
    main()
